name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        cibuildwheel: ["cp39", "cp310", "cp311", "cp312"]
        exclude:
          - python-version: "3.9"
            cibuildwheel: "cp310"
          - python-version: "3.9"
            cibuildwheel: "cp311"
          - python-version: "3.9"
            cibuildwheel: "cp312"
          - python-version: "3.10"
            cibuildwheel: "cp39"
          - python-version: "3.10"
            cibuildwheel: "cp311"
          - python-version: "3.10"
            cibuildwheel: "cp312"
          - python-version: "3.11"
            cibuildwheel: "cp39"
          - python-version: "3.11"
            cibuildwheel: "cp310"
          - python-version: "3.11"
            cibuildwheel: "cp312"
          - python-version: "3.12"
            cibuildwheel: "cp39"
          - python-version: "3.12"
            cibuildwheel: "cp310"
          - python-version: "3.12"
            cibuildwheel: "cp311"

    steps:
    - uses: actions/checkout@v4

    - uses: actions-ext/python/setup@main
      with:
        version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make develop
      if: matrix.os != 'windows-latest'

    - name: Install dependencies
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        make develop
      shell: cmd
      if: matrix.os == 'windows-latest'

    - name: Lint
      run: make lint
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'

    - name: Checks
      run: make checks
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'

    - name: Install build dependencies
      run: pip install cibuildwheel

    - name: Build (Linux)
      run: make build-cibw
      env:
        CIBW_BUILD: "${{ matrix.cibuildwheel }}-manylinux*"
        CIBW_BUILD_VERBOSITY: 3
      if: matrix.os == 'ubuntu-latest'

    - name: Build (Macos)
      run: make build-cibw
      env:
        CIBW_BUILD: "${{ matrix.cibuildwheel }}-macos*"
        CIBW_BUILD_VERBOSITY: 3
      if: matrix.os == 'macos-latest'

    - name: Build (Windows)
      run: make build-cibw
      env:
        CIBW_BUILD: "${{ matrix.cibuildwheel }}-win_amd64"
        CIBW_BEFORE_ALL: call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      if: matrix.os == 'windows-latest'

    - name: Test
      run: make coverage

    - name: Upload test results (Python)
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: junit.xml
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/junit.xml'
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{matrix.os}}-${{matrix.python-version}}
        path: dist
